services:
    glint:
        image: glint
        container_name: glint-get
        volumes:
            - "${DB_DIR}:/data"
            - "${DB_DIR}:/logs"
        build:
            context: ./
            dockerfile: getdata.Dockerfile
        environment:
            - DOCKERCONTAINER=TRUE
