services:
    scraper:
        image: scraper
        container_name: glint-scraper
        build:
            context: ./
            dockerfile: getdata.Dockerfile
        environment:
            - DOCKERCONTAINER=TRUE
        depends_on:
            - storer
    storer:
        image: postgres:latest
        container_name: glint-storer
        privileged: true
        command:
            --port 5432
networks:
    glint-network:
        driver: bridge
        external: true